import type { KnowledgeEntry } from "./types";

export const KNOWLEDGE_REGISTRY: KnowledgeEntry[] = [
  {
    id: "add_product",
    title: "Add & Manage Products",
    category: "catalog",
    keywords: [
      "product",
      "products",
      "prduct",
      "prodict",
      "add product",
      "new product",
      "nayi product",
      "item add",
      "saman add",
      "chiz add",
      "product kahan sy add karni hy",
      "product kaise add karun",
      "product add",
      "create product",
    ],
    navigationPath: ["Catalog", "Products", "Add Product"],
    route: "/admin/products",
    actionLabel: "Open Products Page",
    instructionsUrdu:
      "Product add karne ke liye left sidebar mein **Catalog → Products** par jayen. Phir top-right par **'Add Product'** button par click karein. Product ka title, description, price, category, images, aur stock fill karke **Save** karein.",
    instructionsEnglish:
      "To add a new product, go to Catalog → Products from the left sidebar, click the 'Add Product' button at the top right, fill in the details (title, price, category, images, stock), and click Save.",
    exampleQuestions: [
      "Product kahan sy add karni hy?",
      "Nayi product kaise add karun?",
      "How do I add a new product?",
    ],
  },
  {
    id: "create_category",
    title: "Manage Categories",
    category: "catalog",
    keywords: [
      "category",
      "categories",
      "katgory",
      "kategori",
      "catgory",
      "add category",
      "nayi category",
      "category kesy bnani hy",
      "category kaise banaun",
      "collection category",
      "create category",
    ],
    navigationPath: ["Catalog", "Categories"],
    route: "/admin/categories",
    actionLabel: "Open Categories",
    instructionsUrdu:
      "Category banane ke liye left sidebar mein **Catalog → Categories** par jayen. Phir **'Add Category'** button par click karke Name, Slug, Description aur Image upload karke **Save** karein.",
    instructionsEnglish:
      "To create a category, navigate to Catalog → Categories from the left sidebar, click 'Add Category', enter the name, slug, description, and image, then click Save.",
    exampleQuestions: [
      "Category kesy bnani hy?",
      "Nayi category kaise add karun?",
      "Where do I manage product categories?",
    ],
  },
  {
    id: "manage_brands",
    title: "Manage Brands",
    category: "catalog",
    keywords: [
      "brand",
      "brands",
      "add brand",
      "company",
      "brand kaise add karun",
      "nayi brand",
      "create brand",
    ],
    navigationPath: ["Catalog", "Brands"],
    route: "/admin/brands",
    actionLabel: "Open Brands",
    instructionsUrdu:
      "Brands manage karne ke liye left sidebar mein **Catalog → Brands** par jayen. Wahan se aap naye brands add kar sakte hain, logos upload kar sakte hain aur unhe active/disabled kar sakte hain.",
    instructionsEnglish:
      "To manage brands, go to Catalog → Brands in the left menu. You can add new brands, upload brand logos, and toggle active status.",
    exampleQuestions: ["Brand kaise add karun?", "Where are brand settings?"],
  },
  {
    id: "manage_inventory",
    title: "Inventory & Stock",
    category: "catalog",
    keywords: [
      "inventory",
      "stock",
      "quantity",
      "stock check",
      "stock update",
      "low stock",
      "kitna stock hy",
      "stock adjustment",
    ],
    navigationPath: ["Catalog", "Inventory"],
    route: "/admin/inventory",
    actionLabel: "Open Inventory",
    instructionsUrdu:
      "Inventory aur Stock levels check ya update karne ke liye left sidebar mein **Catalog → Inventory** par jayen. Aap har product aur variant ka available stock inline edit kar sakte hain.",
    instructionsEnglish:
      "To manage stock levels, go to Catalog → Inventory. You can update available quantities inline for products and variants.",
    exampleQuestions: ["Stock kaise update karun?", "Where is inventory management?"],
  },
  {
    id: "manage_menus",
    title: "Header & Footer Navigation Menus",
    category: "content",
    keywords: [
      "menu",
      "menus",
      "tab",
      "tabs",
      "new tab",
      "navigation",
      "header menu",
      "footer menu",
      "menu item",
      "menu me item kesy add karna hy",
      "navbar",
      "navigation link",
      "menu me ik new tab add krna hy kesy ho ga",
      "new tab add",
    ],
    navigationPath: ["Content", "Menus"],
    route: "/admin/menus",
    actionLabel: "Open Menu Editor",
    instructionsUrdu:
      "Navigation Menu me naya tab/item add karne ke liye left sidebar mein **Content → Menus** par jayen. Select karein **Header Navigation** ya **Footer Menu**, phir **'Add Navigation Item'** par click karke Label (e.g. Sale, Contact) aur Link enter karke **Save Navigation** par click karein.",
    instructionsEnglish:
      "To add a new navigation tab or link, go to Content → Menus from the left sidebar. Select Header or Footer menu, click 'Add Navigation Item', enter the label and link, then click Save.",
    exampleQuestions: [
      "Menu me ik new tab add krna hy kesy ho ga?",
      "Header menu me new link kaise add karun?",
    ],
  },
  {
    id: "manage_pages",
    title: "Custom Pages (CMS)",
    category: "content",
    keywords: [
      "page",
      "pages",
      "cms",
      "privacy policy",
      "terms",
      "about us page",
      "custom page",
      "naya page",
    ],
    navigationPath: ["Content", "Pages"],
    route: "/admin/pages",
    actionLabel: "Open Pages",
    instructionsUrdu:
      "Custom pages jaise Privacy Policy, Terms & Conditions, ya About Us manage karne ke liye **Content → Pages** par jayen. Aap naya page create kar sakte hain aur content edit kar sakte hain.",
    instructionsEnglish:
      "To edit or create CMS pages, go to Content → Pages. You can manage custom content for Terms, Privacy, About, and custom pages.",
    exampleQuestions: ["Privacy Policy page kaise edit karun?", "Naya page kaise banaun?"],
  },
  {
    id: "whatsapp_settings",
    title: "WhatsApp Chat & Floating Button",
    category: "settings",
    keywords: [
      "whatsapp",
      "wahtsapp",
      "watsapp",
      "wasap",
      "wtsap",
      "whatsaap",
      "whatapp",
      "whatsapp number",
      "whatsapp float",
      "whatsapp button",
      "whatsapp message",
      "chat button",
      "storefront chat",
      "customer chat",
    ],
    navigationPath: ["Settings", "WhatsApp"],
    route: "/admin/settings",
    actionLabel: "Open WhatsApp Settings",
    instructionsUrdu:
      "Storefront par WhatsApp Chat Button active karne aur WhatsApp number add karne ke liye left sidebar mein **Settings** par jayen, phir **WhatsApp** tab par click karein.\n1. **Enable WhatsApp Chat Button** ko check karein.\n2. Apna Phone Number (e.g. `923001234567`) enter karein.\n3. Default welcome message fill karke **Save Settings** par click karein.",
    instructionsEnglish:
      "To enable the floating WhatsApp Chat button on your storefront, go to Settings → WhatsApp tab. Enable the toggle, enter your phone number with country code (e.g. 923001234567), set your default message, and click Save Settings.",
    exampleQuestions: [
      "WhatsApp number add krna hy kesy ho ga?",
      "Storefront par whatsapp chat button kaise lagayein?",
      "Where are WhatsApp settings?",
    ],
  },
  {
    id: "payment_settings",
    title: "Payment Methods & Gateways",
    category: "settings",
    keywords: [
      "payment",
      "payments",
      "jazzcash",
      "easypaisa",
      "cod",
      "cash on delivery",
      "bank transfer",
      "payment gateway",
      "paise receive",
    ],
    navigationPath: ["Settings", "Payments"],
    route: "/admin/settings",
    actionLabel: "Open Payment Settings",
    instructionsUrdu:
      "Payment options (Cash on Delivery, JazzCash, EasyPaisa, Bank Transfer) enable ya update karne ke liye **Settings → Payments** tab par jayen. Apne account details enter karke **Save Settings** par click karein.",
    instructionsEnglish:
      "To configure payment options such as Cash on Delivery, JazzCash, EasyPaisa, or Bank Transfer, go to Settings → Payments tab, enter your details, and click Save Settings.",
    exampleQuestions: [
      "JazzCash/EasyPaisa account kaise add karun?",
      "Cash on Delivery (COD) kaise enable karun?",
    ],
  },
  {
    id: "shipping_settings",
    title: "Shipping & Delivery Rates",
    category: "settings",
    keywords: [
      "shipping",
      "delivery",
      "delivery charges",
      "shipping rate",
      "courier",
      "free shipping",
      "delivery rate",
    ],
    navigationPath: ["Settings", "Shipping"],
    route: "/admin/settings",
    actionLabel: "Open Shipping Settings",
    instructionsUrdu:
      "Delivery charges aur shipping rules set karne ke liye **Settings → Shipping** tab par jayen. Wahan se Flat Shipping Rate, Free Shipping Threshold, aur Order Tracking option set karke **Save Settings** karein.",
    instructionsEnglish:
      "To manage delivery charges and shipping rules, go to Settings → Shipping tab. Configure flat rates, free shipping thresholds, and tracking options, then Save.",
    exampleQuestions: [
      "Delivery charges kaise set karun?",
      "Free shipping threshold kaise lagayein?",
    ],
  },
  {
    id: "customize_homepage",
    title: "Customize Homepage & Layout",
    category: "appearance",
    keywords: [
      "homepage",
      "homepage customize",
      "home page",
      "homepage customize kesy krni hy",
      "customize homepage",
      "homepage sections",
      "home page section",
      "featured products section",
    ],
    navigationPath: ["Appearance", "Customize Storefront"],
    route: "/admin/appearance/customize",
    actionLabel: "Customize Storefront",
    instructionsUrdu:
      "Homepage layout aur sections edit karne ke liye **Appearance → Customize Storefront** par jayen. Wahan se aap Hero Banners, Featured Categories, Best Sellers, Promo Banners ko drag & drop, edit aur toggle kar sakte hain.",
    instructionsEnglish:
      "To customize your homepage layout, go to Appearance → Customize Storefront. Configure, reorder, and toggle Hero Banners, Featured Collections, and Product grids.",
    exampleQuestions: [
      "Homepage customize kesy krni hy?",
      "Home page par products kaise change karun?",
    ],
  },
  {
    id: "add_hero_slide",
    title: "Add Hero Slider & Promo Banners",
    category: "appearance",
    keywords: [
      "slider",
      "slides",
      "slide",
      "hero slide",
      "slider image",
      "slider me new image kesy lagani hy",
      "banner",
      "promo banner",
      "slider update",
    ],
    navigationPath: ["Appearance", "Customize Storefront", "Hero Banners"],
    route: "/admin/appearance/customize",
    actionLabel: "Manage Banners & Slider",
    instructionsUrdu:
      "Slider mein naye banners lagane ke liye **Appearance → Customize Storefront** par jayen. **'Hero Banners'** section mein image upload karein, Title & URL set karein aur Save karein.",
    instructionsEnglish:
      "To add or update hero slider banners, navigate to Appearance → Customize Storefront, select Hero Banners section, upload banner graphic, and Save.",
    exampleQuestions: [
      "Slider me new image kesy lagani hy?",
      "Main banner kaise change karun?",
    ],
  },
  {
    id: "change_theme",
    title: "Storefront Themes Catalog",
    category: "appearance",
    keywords: [
      "theme",
      "themes",
      "change theme",
      "theme catalog",
      "theme kesy change krni hy",
      "meri current theme konsi hy",
      "new theme",
      "design theme",
    ],
    navigationPath: ["Appearance", "Theme Catalog"],
    route: "/admin/appearance/themes",
    actionLabel: "Open Theme Catalog",
    instructionsUrdu:
      "Store ki theme badalne ke liye **Appearance → Theme Catalog** par jayen. Wahan se kisi bhi theme ko 1-click me preview aur **'Activate Theme'** kar sakte hain.",
    instructionsEnglish:
      "To change your store theme, go to Appearance → Theme Catalog. Browse available pre-built themes, preview them, and click 'Activate Theme'.",
    exampleQuestions: [
      "Theme kesy change krni hy?",
      "Theme catalog kahan hy?",
    ],
  },
  {
    id: "popups_modals",
    title: "Popups & Modals",
    category: "appearance",
    keywords: [
      "popup",
      "popups",
      "modal",
      "modals",
      "announcement bar",
      "discount popup",
      "banner popup",
    ],
    navigationPath: ["Appearance", "Popups & Modals"],
    route: "/admin/appearance/popups",
    actionLabel: "Open Popups Settings",
    instructionsUrdu:
      "Storefront promotional popups ya announcement modals manage karne ke liye **Appearance → Popups & Modals** par jayen. Title, discount code, image aur delay set karke Publish karein.",
    instructionsEnglish:
      "To configure promotional popups or announcement modals on your storefront, go to Appearance → Popups & Modals.",
    exampleQuestions: ["Popup banner kaise lagayein?", "Discount popup kaise enable karun?"],
  },
  {
    id: "view_orders",
    title: "Order Management & Tracking",
    category: "sales",
    keywords: [
      "order",
      "orders",
      "order status",
      "tracking",
      "courier tracking",
      "courier",
      "order history",
      "pending orders",
    ],
    navigationPath: ["Sales", "Orders"],
    route: "/admin/orders",
    actionLabel: "Open Orders",
    instructionsUrdu:
      "Orders dekhne aur process karne ke liye **Sales → Orders** par jayen. Har order par status badlein (Processing, Dispatched, Delivered), tracking consignment ID add karein aur customer ko WhatsApp updates bhejain.",
    instructionsEnglish:
      "To view and fulfill customer orders, go to Sales → Orders. Update order statuses, assign tracking consignment numbers, and generate tracking links.",
    exampleQuestions: ["Orders kahan dikhte hain?", "Consignment number kaise enter karun?"],
  },
  {
    id: "view_customers",
    title: "Customer Profiles",
    category: "sales",
    keywords: [
      "customer",
      "customers",
      "users",
      "client list",
      "customer orders",
    ],
    navigationPath: ["Sales", "Customers"],
    route: "/admin/customers",
    actionLabel: "Open Customers",
    instructionsUrdu:
      "Store customers aur unki order history inspect karne ke liye **Sales → Customers** par jayen.",
    instructionsEnglish:
      "To manage customer accounts and order history, navigate to Sales → Customers.",
    exampleQuestions: ["Customer history kaise dekhun?", "Where are customer accounts?"],
  },
  {
    id: "manage_reviews",
    title: "Customer Reviews",
    category: "content",
    keywords: [
      "review",
      "reviews",
      "rating",
      "ratings",
      "customer feedback",
      "review approve",
    ],
    navigationPath: ["Content", "Reviews"],
    route: "/admin/reviews",
    actionLabel: "Open Reviews",
    instructionsUrdu:
      "Customer reviews aur ratings ko approve, reject ya delete karne ke liye **Content → Reviews** par jayen.",
    instructionsEnglish:
      "To moderate and manage customer reviews, navigate to Content → Reviews.",
    exampleQuestions: ["Reviews kaise approve karun?", "Where do I see product ratings?"],
  },
  {
    id: "blog_posts",
    title: "Blog Posts & Articles",
    category: "content",
    keywords: ["blog", "blogs", "blog post", "article", "news", "post"],
    navigationPath: ["Content", "Blog Posts"],
    route: "/admin/blog-posts",
    actionLabel: "Open Blog Posts",
    instructionsUrdu:
      "Store blog articles publish aur edit karne ke liye **Content → Blog Posts** par jayen.",
    instructionsEnglish: "To publish and manage blog posts, go to Content → Blog Posts.",
    exampleQuestions: ["Blog post kaise add karun?", "Where to manage articles?"],
  },
  {
    id: "manage_faqs",
    title: "FAQs Management",
    category: "content",
    keywords: ["faq", "faqs", "questions", "frequently asked questions", "sawal"],
    navigationPath: ["Content", "FAQs"],
    route: "/admin/faqs",
    actionLabel: "Open FAQs",
    instructionsUrdu:
      "Storefront FAQ section me masail aur jawabat add karne ke liye **Content → FAQs** par jayen.",
    instructionsEnglish: "To manage frequently asked questions, go to Content → FAQs.",
    exampleQuestions: ["FAQs kaise edit karun?", "Frequently asked questions section?"],
  },
  {
    id: "analytics_reports",
    title: "Analytics & Sales Reports",
    category: "sales",
    keywords: ["analytics", "reports", "report", "sales report", "traffic", "views"],
    navigationPath: ["Sales", "Analytics"],
    route: "/admin/analytics",
    actionLabel: "Open Analytics",
    instructionsUrdu:
      "Store sales graphs, traffic visitors, aur conversion analytics dekhne ke liye **Sales → Analytics** par jayen.",
    instructionsEnglish: "To view sales graphs and visitor metrics, go to Sales → Analytics.",
    exampleQuestions: ["Store analytics kahan hain?", "Sales report kaise dekhun?"],
  },
  {
    id: "finance_payouts",
    title: "Finance & Payouts",
    category: "sales",
    keywords: ["finance", "payouts", "revenue", "earnings", "ledger", "commission"],
    navigationPath: ["Sales", "Finance"],
    route: "/admin/finance",
    actionLabel: "Open Finance",
    instructionsUrdu:
      "Store gross revenue, net profit, aur payout history dekhne ke liye **Sales → Finance** par jayen.",
    instructionsEnglish: "To inspect gross revenue and earnings ledgers, go to Sales → Finance.",
    exampleQuestions: ["Finance summary kahan hy?", "Where to check earnings?"],
  },
  {
    id: "manage_settings",
    title: "Store Settings Center",
    category: "settings",
    keywords: ["settings", "store settings", "general settings", "store details"],
    navigationPath: ["Settings"],
    route: "/admin/settings",
    actionLabel: "Open Store Settings",
    instructionsUrdu:
      "Store details, payments, shipping, WhatsApp, branding, taxes, aur integrations manage karne ke liye left sidebar ke end me **Settings** par click karein.",
    instructionsEnglish:
      "To manage all store configurations, go to Settings from the main sidebar.",
    exampleQuestions: ["Store settings kahan hain?", "Where are store configurations?"],
  },
];
