import type { KnowledgeEntry } from "./types";

export const KNOWLEDGE_REGISTRY: KnowledgeEntry[] = [
  {
    id: "add_product",
    title: "Add & Manage Products",
    category: "catalog",
    keywords: [
      "product",
      "products",
      "prduct",
      "prodict",
      "add product",
      "new product",
      "nayi product",
      "item add",
      "saman add",
      "chiz add",
      "product kahan sy add karni hy",
      "product kaise add karun",
      "product add",
      "create product",
    ],
    navigationPath: ["Catalog", "Products", "Add Product"],
    route: "/admin/products",
    actionLabel: "Open Products Page",
    instructionsUrdu:
      "Product add karne ke liye left sidebar mein **Catalog → Products** par jayen. Phir top-right par **'Add Product'** button par click karein. Product ka title, description, price, category, images, aur stock fill karke **Save** karein.",
    instructionsEnglish:
      "To add a new product, go to Catalog → Products from the left sidebar, click the 'Add Product' button at the top right, fill in the details (title, price, category, images, stock), and click Save.",
    exampleQuestions: [
      "Product kahan sy add karni hy?",
      "Nayi product kaise add karun?",
      "How do I add a new product?",
    ],
  },
  {
    id: "create_category",
    title: "Manage Categories",
    category: "catalog",
    keywords: [
      "category",
      "categories",
      "katgory",
      "kategori",
      "catgory",
      "add category",
      "nayi category",
      "category kesy bnani hy",
      "category kaise banaun",
      "collection category",
      "create category",
    ],
    navigationPath: ["Catalog", "Categories"],
    route: "/admin/categories",
    actionLabel: "Open Categories",
    instructionsUrdu:
      "Category banane ke liye left sidebar mein **Catalog → Categories** par jayen. Phir **'Add Category'** button par click karke Name, Slug, Description aur Image upload karke **Save** karein.",
    instructionsEnglish:
      "To create a category, navigate to Catalog → Categories from the left sidebar, click 'Add Category', enter the name, slug, description, and image, then click Save.",
    exampleQuestions: [
      "Category kesy bnani hy?",
      "Nayi category kaise add karun?",
      "Where do I manage product categories?",
    ],
  },
  {
    id: "manage_brands",
    title: "Manage Brands",
    category: "catalog",
    keywords: [
      "brand",
      "brands",
      "add brand",
      "company",
      "brand kaise add karun",
      "nayi brand",
      "create brand",
    ],
    navigationPath: ["Catalog", "Brands"],
    route: "/admin/brands",
    actionLabel: "Open Brands",
    instructionsUrdu:
      "Brands manage karne ke liye left sidebar mein **Catalog → Brands** par jayen. Wahan se aap naye brands add kar sakte hain, logos upload kar sakte hain aur unhe active/disabled kar sakte hain.",
    instructionsEnglish:
      "To manage brands, go to Catalog → Brands in the left menu. You can add new brands, upload brand logos, and toggle active status.",
    exampleQuestions: ["Brand kaise add karun?", "Where are brand settings?"],
  },
  {
    id: "manage_inventory",
    title: "Inventory & Stock",
    category: "catalog",
    keywords: [
      "inventory",
      "stock",
      "quantity",
      "stock check",
      "stock update",
      "low stock",
      "kitna stock hy",
      "stock adjustment",
    ],
    navigationPath: ["Catalog", "Inventory"],
    route: "/admin/inventory",
    actionLabel: "Open Inventory",
    instructionsUrdu:
      "Inventory aur Stock levels check ya update karne ke liye left sidebar mein **Catalog → Inventory** par jayen. Aap har product aur variant ka available stock inline edit kar sakte hain.",
    instructionsEnglish:
      "To manage stock levels, go to Catalog → Inventory. You can update available quantities inline for products and variants.",
    exampleQuestions: ["Stock kaise update karun?", "Where is inventory management?"],
  },
  {
    id: "manage_menus",
    title: "Header & Footer Navigation Menus",
    category: "content",
    keywords: [
      "menu",
      "menus",
      "tab",
      "tabs",
      "new tab",
      "navigation",
      "header menu",
      "footer menu",
      "menu item",
      "menu me item kesy add karna hy",
      "navbar",
      "navigation link",
      "menu me ik new tab add krna hy kesy ho ga",
      "new tab add",
    ],
    navigationPath: ["Content", "Menus"],
    route: "/admin/menus",
    actionLabel: "Open Menu Editor",
    instructionsUrdu:
      "Navigation Menu me naya tab/item add karne ke liye left sidebar mein **Content → Menus** par jayen. Select karein **Header Navigation** ya **Footer Menu**, phir **'Add Navigation Item'** par click karke Label (e.g. Sale, Contact) aur Link enter karke **Save Navigation** par click karein.",
    instructionsEnglish:
      "To add a new navigation tab or link, go to Content → Menus from the left sidebar. Select Header or Footer menu, click 'Add Navigation Item', enter the label and link, then click Save.",
    exampleQuestions: [
      "Menu me ik new tab add krna hy kesy ho ga?",
      "Header menu me new link kaise add karun?",
    ],
  },
  {
    id: "manage_pages",
    title: "Custom Pages (CMS)",
    category: "content",
    keywords: [
      "page",
      "pages",
      "cms",
      "privacy policy",
      "terms",
      "about us page",
      "custom page",
      "naya page",
    ],
    navigationPath: ["Content", "Pages"],
    route: "/admin/pages",
    actionLabel: "Open Pages",
    instructionsUrdu:
      "Custom pages jaise Privacy Policy, Terms & Conditions, ya About Us manage karne ke liye **Content → Pages** par jayen. Aap naya page create kar sakte hain aur content edit kar sakte hain.",
    instructionsEnglish:
      "To edit or create CMS pages, go to Content → Pages. You can manage custom content for Terms, Privacy, About, and custom pages.",
    exampleQuestions: ["Privacy Policy page kaise edit karun?", "Naya page kaise banaun?"],
  },
  {
    id: "whatsapp_settings",
    title: "WhatsApp Chat & Floating Button",
    category: "settings",
    keywords: [
      "whatsapp",
      "wahtsapp",
      "watsapp",
      "wasap",
      "wtsap",
      "whatsaap",
      "whatapp",
      "whatsapp number",
      "whatsapp float",
      "whatsapp button",
      "whatsapp message",
      "chat button",
      "storefront chat",
      "customer chat",
    ],
    navigationPath: ["Settings", "WhatsApp"],
    route: "/admin/settings",
    actionLabel: "Open WhatsApp Settings",
    instructionsUrdu:
      "Storefront par WhatsApp Chat Button active karne aur WhatsApp number add karne ke liye left sidebar mein **Settings** par jayen, phir **WhatsApp** tab par click karein.\n1. **Enable WhatsApp Chat Button** ko check karein.\n2. Apna Phone Number (e.g. `923001234567`) enter karein.\n3. Default welcome message fill karke **Save Settings** par click karein.",
    instructionsEnglish:
      "To enable the floating WhatsApp Chat button on your storefront, go to Settings → WhatsApp tab. Enable the toggle, enter your phone number with country code (e.g. 923001234567), set your default message, and click Save Settings.",
    exampleQuestions: [
      "WhatsApp number add krna hy kesy ho ga?",
      "Storefront par whatsapp chat button kaise lagayein?",
      "Where are WhatsApp settings?",
    ],
  },
  {
    id: "payment_settings",
    title: "Payment Methods & Gateways",
    category: "settings",
    keywords: [
      "payment",
      "payments",
      "jazzcash",
      "easypaisa",
      "cod",
      "cash on delivery",
      "bank transfer",
      "payment gateway",
      "paise receive",
    ],
    navigationPath: ["Settings", "Payments"],
    route: "/admin/settings",
    actionLabel: "Open Payment Settings",
    instructionsUrdu:
      "Payment options (Cash on Delivery, JazzCash, EasyPaisa, Bank Transfer) enable ya update karne ke liye **Settings → Payments** tab par jayen. Apne account details enter karke **Save Settings** par click karein.",
    instructionsEnglish:
      "To configure payment options such as Cash on Delivery, JazzCash, EasyPaisa, or Bank Transfer, go to Settings → Payments tab, enter your details, and click Save Settings.",
    exampleQuestions: [
      "JazzCash/EasyPaisa account kaise add karun?",
      "Cash on Delivery (COD) kaise enable karun?",
    ],
  },
  {
    id: "shipping_settings",
    title: "Shipping & Delivery Rates",
    category: "settings",
    keywords: [
      "shipping",
      "delivery",
      "delivery charges",
      "shipping rate",
      "courier",
      "free shipping",
      "delivery rate",
    ],
    navigationPath: ["Settings", "Shipping"],
    route: "/admin/settings",
    actionLabel: "Open Shipping Settings",
    instructionsUrdu:
      "Delivery charges aur shipping rules set karne ke liye **Settings → Shipping** tab par jayen. Wahan se Flat Shipping Rate, Free Shipping Threshold, aur Order Tracking option set karke **Save Settings** karein.",
    instructionsEnglish:
      "To manage delivery charges and shipping rules, go to Settings → Shipping tab. Configure flat rates, free shipping thresholds, and tracking options, then Save.",
    exampleQuestions: [
      "Delivery charges kaise set karun?",
      "Free shipping threshold kaise lagayein?",
    ],
  },
  {
    id: "customize_homepage",
    title: "Customize Homepage & Layout",
    category: "appearance",
    keywords: [
      "homepage",
      "homepage customize",
      "home page",
      "homepage customize kesy krni hy",
      "customize homepage",
      "homepage sections",
      "home page section",
      "featured products section",
    ],
    navigationPath: ["Appearance", "Customize Storefront"],
    route: "/admin/appearance/customize",
    actionLabel: "Customize Storefront",
    instructionsUrdu:
      "Homepage layout aur sections edit karne ke liye **Appearance → Customize Storefront** par jayen. Wahan se aap Hero Banners, Featured Categories, Best Sellers, Promo Banners ko drag & drop, edit aur toggle kar sakte hain.",
    instructionsEnglish:
      "To customize your homepage layout, go to Appearance → Customize Storefront. Configure, reorder, and toggle Hero Banners, Featured Collections, and Product grids.",
    exampleQuestions: [
      "Homepage customize kesy krni hy?",
      "Home page par products kaise change karun?",
    ],
  },
  {
    id: "add_hero_slide",
    title: "Add Hero Slider & Promo Banners",
    category: "appearance",
    keywords: [
      "slider",
      "slides",
      "slide",
      "hero slide",
      "slider image",
      "slider me new image kesy lagani hy",
      "banner",
      "promo banner",
      "slider update",
    ],
    navigationPath: ["Appearance", "Customize Storefront", "Hero Banners"],
    route: "/admin/appearance/customize",
    actionLabel: "Manage Banners & Slider",
    instructionsUrdu:
      "Slider mein naye banners lagane ke liye **Appearance → Customize Storefront** par jayen. **'Hero Banners'** section mein image upload karein, Title & URL set karein aur Save karein.",
    instructionsEnglish:
      "To add or update hero slider banners, navigate to Appearance → Customize Storefront, select Hero Banners section, upload banner graphic, and Save.",
    exampleQuestions: [
      "Slider me new image kesy lagani hy?",
      "Main banner kaise change karun?",
    ],
  },
  {
    id: "change_theme",
    title: "Storefront Themes Catalog",
    category: "appearance",
    keywords: [
      "theme",
      "themes",
      "change theme",
      "theme catalog",
      "theme kesy change krni hy",
      "meri current theme konsi hy",
      "new theme",
      "design theme",
    ],
    navigationPath: ["Appearance", "Theme Catalog"],
    route: "/admin/appearance/themes",
    actionLabel: "Open Theme Catalog",
    instructionsUrdu:
      "Store ki theme badalne ke liye **Appearance → Theme Catalog** par jayen. Wahan se kisi bhi theme ko 1-click me preview aur **'Activate Theme'** kar sakte hain.",
    instructionsEnglish:
      "To change your store theme, go to Appearance → Theme Catalog. Browse available pre-built themes, preview them, and click 'Activate Theme'.",
    exampleQuestions: [
      "Theme kesy change krni hy?",
      "Theme catalog kahan hy?",
    ],
  },
  {
    id: "popups_modals",
    title: "Popups & Modals",
    category: "appearance",
    keywords: [
      "popup",
      "popups",
      "modal",
      "modals",
      "announcement bar",
      "discount popup",
      "banner popup",
    ],
    navigationPath: ["Appearance", "Popups & Modals"],
    route: "/admin/appearance/popups",
    actionLabel: "Open Popups Settings",
    instructionsUrdu:
      "Storefront promotional popups ya announcement modals manage karne ke liye **Appearance → Popups & Modals** par jayen. Title, discount code, image aur delay set karke Publish karein.",
    instructionsEnglish:
      "To configure promotional popups or announcement modals on your storefront, go to Appearance → Popups & Modals.",
    exampleQuestions: ["Popup banner kaise lagayein?", "Discount popup kaise enable karun?"],
  },
  {
    id: "view_orders",
    title: "Order Management & Tracking",
    category: "sales",
    keywords: [
      "order",
      "orders",
      "order status",
      "tracking",
      "courier tracking",
      "courier",
      "order history",
      "pending orders",
    ],
    navigationPath: ["Sales", "Orders"],
    route: "/admin/orders",
    actionLabel: "Open Orders",
    instructionsUrdu:
      "Orders dekhne aur process karne ke liye **Sales → Orders** par jayen. Har order par status badlein (Confirmed, Processing, Packed, Dispatched, Delivered), tracking/consignment number add karein aur customer ko WhatsApp updates bhejain. **COD orders** pehle order page ke **Order Verification** card se Confirm karne zaroori hain - us se pehle status aage nahi badhega aur courier/shipment details save nahi hongi. Order page par customer ki **Delivery Preference** (Home ya Office 9 AM-5 PM) bhi nazar aati hai.",
    instructionsEnglish:
      "To view and fulfill orders, go to Sales → Orders. Update statuses (Confirmed, Processing, Packed, Dispatched, Delivered), add tracking/consignment numbers and send WhatsApp updates. COD orders must first be confirmed from the Order Verification card on the order page - until then the status can't move forward and shipment details can't be saved. The order page also shows the customer's Delivery Preference (Home, or Office 9 AM-5 PM).",
    exampleQuestions: ["Orders kahan dikhte hain?", "Consignment number kaise enter karun?"],
  },
  {
    id: "view_customers",
    title: "Customer Profiles",
    category: "sales",
    keywords: [
      "customer",
      "customers",
      "users",
      "client list",
      "customer orders",
    ],
    navigationPath: ["Sales", "Customers"],
    route: "/admin/customers",
    actionLabel: "Open Customers",
    instructionsUrdu:
      "Store customers aur unki order history inspect karne ke liye **Sales → Customers** par jayen.",
    instructionsEnglish:
      "To manage customer accounts and order history, navigate to Sales → Customers.",
    exampleQuestions: ["Customer history kaise dekhun?", "Where are customer accounts?"],
  },
  {
    id: "manage_reviews",
    title: "Customer Reviews",
    category: "content",
    keywords: [
      "review",
      "reviews",
      "rating",
      "ratings",
      "customer feedback",
      "review approve",
    ],
    navigationPath: ["Content", "Reviews"],
    route: "/admin/reviews",
    actionLabel: "Open Reviews",
    instructionsUrdu:
      "Customer reviews aur ratings ko approve, reject ya delete karne ke liye **Content → Reviews** par jayen.",
    instructionsEnglish:
      "To moderate and manage customer reviews, navigate to Content → Reviews.",
    exampleQuestions: ["Reviews kaise approve karun?", "Where do I see product ratings?"],
  },
  {
    id: "blog_posts",
    title: "Blog Posts & Articles",
    category: "content",
    keywords: ["blog", "blogs", "blog post", "article", "news", "post"],
    navigationPath: ["Content", "Blog Posts"],
    route: "/admin/blog-posts",
    actionLabel: "Open Blog Posts",
    instructionsUrdu:
      "Store blog articles publish aur edit karne ke liye **Content → Blog Posts** par jayen.",
    instructionsEnglish: "To publish and manage blog posts, go to Content → Blog Posts.",
    exampleQuestions: ["Blog post kaise add karun?", "Where to manage articles?"],
  },
  {
    id: "manage_faqs",
    title: "FAQs Management",
    category: "content",
    keywords: ["faq", "faqs", "questions", "frequently asked questions", "sawal"],
    navigationPath: ["Content", "FAQs"],
    route: "/admin/faqs",
    actionLabel: "Open FAQs",
    instructionsUrdu:
      "Storefront FAQ section me masail aur jawabat add karne ke liye **Content → FAQs** par jayen.",
    instructionsEnglish: "To manage frequently asked questions, go to Content → FAQs.",
    exampleQuestions: ["FAQs kaise edit karun?", "Frequently asked questions section?"],
  },
  {
    id: "analytics_reports",
    title: "Analytics & Sales Reports",
    category: "sales",
    keywords: ["analytics", "reports", "report", "sales report", "traffic", "views"],
    navigationPath: ["Sales", "Analytics"],
    route: "/admin/analytics",
    actionLabel: "Open Analytics",
    instructionsUrdu:
      "Store sales graphs, traffic visitors, aur conversion analytics dekhne ke liye **Sales → Analytics** par jayen.",
    instructionsEnglish: "To view sales graphs and visitor metrics, go to Sales → Analytics.",
    exampleQuestions: ["Store analytics kahan hain?", "Sales report kaise dekhun?"],
  },
  {
    id: "finance_payouts",
    title: "Finance & Payouts",
    category: "sales",
    keywords: ["finance", "payouts", "revenue", "earnings", "ledger", "commission"],
    navigationPath: ["Sales", "Finance"],
    route: "/admin/finance",
    actionLabel: "Open Finance",
    instructionsUrdu:
      "Store gross revenue, net profit, aur payout history dekhne ke liye **Sales → Finance** par jayen.",
    instructionsEnglish: "To inspect gross revenue and earnings ledgers, go to Sales → Finance.",
    exampleQuestions: ["Finance summary kahan hy?", "Where to check earnings?"],
  },
  {
    id: "manage_settings",
    title: "Store Settings Center",
    category: "settings",
    keywords: ["settings", "store settings", "general settings", "store details"],
    navigationPath: ["Settings"],
    route: "/admin/settings",
    actionLabel: "Open Store Settings",
    instructionsUrdu:
      "Store details, payments, shipping, WhatsApp, branding, taxes, aur integrations manage karne ke liye left sidebar ke end me **Settings** par click karein.",
    instructionsEnglish:
      "To manage all store configurations, go to Settings from the main sidebar.",
    exampleQuestions: ["Store settings kahan hain?", "Where are store configurations?"],
  },
  {
    id: "manage_collections",
    title: "Product Collections",
    category: "catalog",
    keywords: [
      "collection",
      "collections",
      "koleksn",
      "product collection",
      "collection kaise banaun",
      "collection kesy bnani hy",
      "create collection",
      "new collection",
    ],
    navigationPath: ["Collections (direct URL - no sidebar link yet)"],
    route: "/admin/collections",
    actionLabel: "Open Collections",
    instructionsUrdu:
      "Collections abhi left sidebar mein nahi hain - inhe manage karne ke liye direct is URL par jayen: **/admin/collections**. Wahan **'Add Collection'** button se naya collection Name aur Slug ke sath bana sakte hain. Kisi product ko us collection mein shamil karne ke liye, us product ki **Edit Product** screen kholein aur **'Collections'** field mein us collection ko check karein.",
    instructionsEnglish:
      "Collections don't have a sidebar link yet - manage them directly at /admin/collections (create, rename, trash). To put a product inside a collection, open that product's Edit page and check it under the 'Collections' field.",
    exampleQuestions: [
      "Collection kaise banani hai?",
      "Product ko collection mein kaise dalein?",
      "Where do I manage collections?",
    ],
  },
  {
    id: "manage_suppliers",
    title: "Suppliers",
    category: "catalog",
    keywords: [
      "supplier",
      "suppliers",
      "vendor",
      "vendors",
      "supplier kaise add karun",
      "supplier banana",
      "create supplier",
    ],
    navigationPath: ["Suppliers (direct URL - no sidebar link yet)"],
    route: "/admin/suppliers",
    actionLabel: "Open Suppliers",
    instructionsUrdu:
      "Suppliers abhi left sidebar mein nahi hain - inhe manage karne ke liye direct is URL par jayen: **/admin/suppliers**. Naya supplier add karke, kisi product ko us supplier se link karne ke liye us product ki **Edit Product** screen mein **'Supplier'** dropdown se select karein.",
    instructionsEnglish:
      "Suppliers don't have a sidebar link yet - manage them directly at /admin/suppliers. After adding a supplier, link a product to it from that product's Edit page using the 'Supplier' dropdown.",
    exampleQuestions: [
      "Supplier kaise add karun?",
      "Product ko supplier se link kaise karein?",
      "Where do I manage suppliers?",
    ],
  },
  {
    id: "manage_announcements",
    title: "Announcement Bars",
    category: "appearance",
    keywords: [
      "announcement",
      "announcements",
      "announcement bar",
      "top bar",
      "notice bar",
      "banner strip",
      "announcement kaise lagayein",
    ],
    navigationPath: ["Appearance", "Customize Storefront", "Homepage builder (Announcement Bars link)"],
    route: "/admin/announcements",
    actionLabel: "Open Announcement Bars",
    instructionsUrdu:
      "Storefront ke top par ek slim announcement bar (jaise 'Free shipping over Rs 2000') dikhane ke liye **/admin/announcements** par jayen (ye link Homepage builder screen se bhi milta hai). **'Add announcement bar'** se text aur priority set karke Save karein - agar ek se zyada bar active hon to sabse high priority wala dikhta hai.",
    instructionsEnglish:
      "To show a slim announcement bar at the top of the storefront, go to /admin/announcements (also linked from the Homepage builder screen). Add a bar with text and priority - when multiple are active, only the highest-priority one shows.",
    exampleQuestions: [
      "Announcement bar kaise lagayein?",
      "Top par notice kaise dikhayein?",
      "Where do I manage the announcement bar?",
    ],
  },
  {
    id: "theme_editor",
    title: "Theme Editor (Colors, Fonts, Layout)",
    category: "appearance",
    keywords: [
      "theme editor",
      "theme colors",
      "theme colour",
      "font family",
      "brand color",
      "typography",
      "border radius",
      "theme customize kaise karein",
      "colors kaise change karein",
    ],
    navigationPath: ["Theme Editor (direct URL - no sidebar link yet)"],
    route: "/admin/theme",
    actionLabel: "Open Theme Editor",
    instructionsUrdu:
      "Ye **Theme Catalog** (jahan aap alag alag pre-built themes ke darmiyan switch karte hain) se alag hai. Apni CURRENT active theme ke colors, font, aur layout customize karne ke liye **/admin/theme** par jayen (abhi sidebar mein link nahi hai). Changes karke tab tak storefront par nazar nahi aayenge jab tak theme ko **Publish** na karein.",
    instructionsEnglish:
      "This is different from the Theme Catalog (which switches between different pre-built themes). To customize your CURRENT active theme's colors, fonts, and layout, go to /admin/theme (no sidebar link yet). Changes only go live on the storefront after you click Publish.",
    exampleQuestions: [
      "Theme editor kahan hai?",
      "Theme ke colors kaise change karun?",
      "Font family kaise badlein?",
    ],
  },
  {
    id: "change_password_store_admin",
    title: "Change Your Store Admin Password",
    category: "settings",
    keywords: [
      "password change",
      "password badalna",
      "apna password",
      "new password set",
      "change my password",
      "update password",
      "pasword",
      "paswrd",
    ],
    navigationPath: ["Settings", "Security", "Change Password"],
    route: "/admin/settings",
    actionLabel: "Open Security Settings",
    instructionsUrdu:
      "Apne Store Admin account ka password (login karte hue) change karne ke liye **Settings → Security** tab par jayen. **Change Password** section mein apna current password aur naya password enter karke Save karein.",
    instructionsEnglish:
      "To change your own Store Admin password while logged in, go to Settings → Security tab, and use the Change Password section (enter your current password and a new one, then save).",
    exampleQuestions: [
      "Apna password kaise change karun?",
      "How do I update my admin password?",
    ],
  },
  {
    id: "forgot_password",
    title: "Forgot Password / Reset Password",
    category: "general",
    keywords: [
      "forgot password",
      "password reset",
      "password bhool gaya",
      "password yaad nahi",
      "reset password",
      "password recover",
      "login nahi ho raha password",
    ],
    navigationPath: ["Admin Login page", "Forgot password?"],
    route: "/admin/login",
    actionLabel: "Open Login Page",
    instructionsUrdu:
      "Agar password yaad nahi hai to Store Admin **Login page** par jayen aur password field ke neeche **'Forgot password?'** link par click karein. Apna admin email enter karein - agar account exist karta hai to ek secure reset link email par bheja jayega. Us link par click karke naya password set karein aur wapas login karein.",
    instructionsEnglish:
      "If you forgot your password, go to the Store Admin Login page and click 'Forgot password?' below the password field. Enter your admin email - if the account exists, a secure reset link is emailed to it. Follow that link to set a new password, then sign in again.",
    exampleQuestions: [
      "Password reset kaise karun?",
      "Password bhool gaya, kya karun?",
      "How do I reset my password?",
    ],
  },
  {
    id: "platform_sender_email",
    title: "Which Email Address Sends Platform Emails",
    category: "general",
    keywords: [
      "email kis address se",
      "sender email",
      "which email sends",
      "platform email",
      "from email",
      "email address bhejta",
    ],
    navigationPath: ["N/A - informational, configured by Super Admin"],
    route: "/admin/settings",
    actionLabel: "Open Settings",
    instructionsUrdu:
      "Webriiz platform ke emails (welcome email, password-setup/reset link) **support@webriiz.com** se bhejte hain. Ye Super Admin-level setting hai, Store Admin se change nahi hoti. (Note: aapke apne storefront ke customer-facing order emails alag hain - wo aapki apni Store Email Settings se bhejte hain, jo aap **Settings → Email** tab se set kar sakte hain.)",
    instructionsEnglish:
      "Webriiz platform emails (welcome email, password-setup/reset link) are sent from support@webriiz.com. This is a Super Admin-level setting and isn't changed from Store Admin. Your own storefront's customer-facing order emails are separate, sent from your own Store Email settings (Settings → Email tab).",
    exampleQuestions: [
      "Email kis address se jayegi?",
      "Which email address do platform emails come from?",
    ],
  },
  {
    id: "welcome_email_after_store_creation",
    title: "Welcome Email After Store Creation",
    category: "general",
    keywords: [
      "store create hone ke baad email",
      "welcome email",
      "owner ko email",
      "account email nahi mila",
      "store banne ke baad",
    ],
    navigationPath: ["N/A - happens automatically when Super Admin creates the store"],
    route: "/admin/login",
    actionLabel: "Open Login Page",
    instructionsUrdu:
      "Jab Super Admin naya store create karta hai, store owner ko ek welcome email jati hai jisme store ka naam, Storefront URL, Store Admin URL, aur ek secure password-setup link hota hai (kabhi bhi plaintext password nahi bheja jata). Us link par click karke apna password set karein, phir Login page se sign in karein. Agar email na mile, spam folder check karein ya Super Admin se resend karwayein.",
    instructionsEnglish:
      "When Super Admin creates a new store, the owner gets a welcome email with the store name, Storefront URL, Store Admin URL, and a secure password-setup link (never a plaintext password). Click that link to set your password, then sign in from the Login page. If it doesn't arrive, check spam or ask your Super Admin to resend it.",
    exampleQuestions: [
      "Store create hone ke baad owner ko email kaise milegi?",
      "How does the store owner receive their welcome email?",
    ],
  },
  {
    id: "custom_domain",
    title: "Connecting a Custom Domain",
    category: "general",
    keywords: [
      "custom domain",
      "domain connect",
      "apna domain",
      "domain kaise lagayein",
      "domain add",
      "own domain",
    ],
    navigationPath: ["Settings", "Domain"],
    route: "/admin/settings",
    actionLabel: "Open Settings",
    instructionsUrdu:
      "**Settings → Domain** kholein aur apna domain likhein (jaise apnastore.com), phir **Add domain** dabayein. Screen par jo DNS records aayenge (TXT, A aur CNAME) unhein apne domain provider (Namecheap, GoDaddy, PKNIC waghaira) ki DNS settings mein bilkul waise hi add karein, phir **Check status** dabayein. Har step ka status nazar aayega. DNS update hone mein kuch minute se 24-48 ghante lag sakte hain. Connect hone ke baad aapka store apnastore.com par aur Store Admin admin.apnastore.com par khulega, purana address khud naye domain par chala jayega, aur SSL (https) free milega. Domain hatana ho to wahin **Disconnect domain** dabayein.",
    instructionsEnglish:
      "Open **Settings → Domain**, enter your domain (e.g. yourstore.com) and press **Add domain**. Add the DNS records shown (TXT, A and CNAME) at your domain provider (Namecheap, GoDaddy, PKNIC...) exactly as listed, then press **Check status** - each step's progress is shown. DNS changes can take from a few minutes up to 24-48 hours. Once connected, your store opens at yourstore.com and Store Admin at admin.yourstore.com, your old address redirects to the new domain, and HTTPS (SSL) is free and automatic. To remove it, use **Disconnect domain** on the same page.",
    exampleQuestions: [
      "Custom domain kaise connect karun?",
      "How do I connect my own domain?",
    ],
  },
  {
    id: "storefront_vs_admin_url",
    title: "Storefront URL vs Store Admin URL",
    category: "general",
    keywords: [
      "store admin url",
      "storefront url",
      "admin url kya hy",
      "difference between storefront and admin",
      "store ka link kya hy",
      "my store url",
    ],
    navigationPath: ["N/A - informational"],
    route: "/admin",
    actionLabel: "Open Dashboard",
    instructionsUrdu:
      "**Storefront URL** wo link hai jo aapke customers dekhte hain (aapki public shopping site, jaise yourstore.webriiz.com). **Store Admin URL** wo separate, private link hai jahan sirf aap login karke apna store manage karte hain (jaise admin-yourstore.webriiz.com). Dono alag domains hain - customer ko kabhi bhi Admin URL nahi dena chahiye.",
    instructionsEnglish:
      "The Storefront URL is the public link your customers browse and shop from (e.g. yourstore.webriiz.com). The Store Admin URL is a separate, private link only you use to log in and manage your store (e.g. admin-yourstore.webriiz.com). They're different domains - never share the Admin URL with a customer.",
    exampleQuestions: [
      "Store Admin URL kya hai?",
      "Storefront aur admin URL mein kya difference hai?",
    ],
  },
  {
    id: "order_delivered_lifecycle",
    title: "What Happens When an Order Is Marked Delivered",
    category: "sales",
    keywords: [
      "order delivered karne ke baad",
      "delivered karne ke baad kya hota",
      "order lifecycle",
      "delivered status effect",
      "after delivered",
    ],
    navigationPath: ["Sales", "Orders", "Order Detail"],
    route: "/admin/orders",
    actionLabel: "Open Orders",
    instructionsUrdu:
      "Jab aap order ko **Delivered** mark karte hain, ye order ki final/terminal state hai - is ke baad koi aur status change (Cancelled ke ilawa koi bhi) allow nahi hota. Order **Delivered** filter tab mein show hone lagta hai, aur customer apne **Order Tracking** page par 'Delivered' status aur poori activity history (Placed → Confirmed → Processing → Packed → Dispatched → Delivered) dekh sakta hai.",
    instructionsEnglish:
      "Marking an order Delivered is its final/terminal state - no further status change is allowed after it. The order then appears under the Delivered filter tab, and the customer sees 'Delivered' plus the full activity timeline (Placed → Confirmed → Processing → Packed → Dispatched → Delivered) on their Order Tracking page.",
    exampleQuestions: [
      "Order delivered karne ke baad kya hota hai?",
      "What happens after I mark an order as delivered?",
    ],
  },
  {
    id: "customer_order_verification",
    title: "How a Customer Tracks/Verifies Their Order",
    category: "sales",
    keywords: [
      "customer order kaise verify",
      "order verify karna",
      "customer order tracking",
      "customer ko order status",
      "order tracking page",
      "track order",
      "customer order verify",
      "order verify",
    ],
    navigationPath: ["Storefront", "Order Tracking page"],
    route: "/admin/orders",
    actionLabel: "Open Orders",
    instructionsUrdu:
      "Customer apna order storefront ke **Order Tracking** page par khud track kar sakta hai: **order number** ke saath checkout par diya hua **email ya phone number** daalein (phone kisi bhi format mein chalega, jaise 0300-1234567 ya +92 300 1234567). Email dena zaroori nahi - sirf phone wale customers bhi track kar sakte hain. Order place hone ke baad 'Track Order Status' button seedha isi page par le jata hai, aur 'Dispatched' WhatsApp message mein bhi tracking link hota hai. Aap khud **Sales → Orders** mein order dekh sakte hain.",
    instructionsEnglish:
      "Customers track their own order on the storefront's Order Tracking page by entering the order number plus the email OR phone number they gave at checkout (any phone format works, e.g. 0300-1234567 or +92 300 1234567). Email is optional - phone-only customers can track too. The 'Track Order Status' button after checkout opens this page directly, and the 'Dispatched' WhatsApp message includes a tracking link. You can look up the same order under Sales → Orders.",
    exampleQuestions: [
      "Customer ka order kaise verify karun?",
      "Customer apna order kaise track karega?",
    ],
  },
  {
    id: "cod_order_verification",
    title: "COD Order Verification (Confirm / Reject)",
    category: "sales",
    keywords: [
      "cod verification",
      "order verification card",
      "order confirm kaise karun",
      "order reject",
      "fake order",
      "risk level",
      "high risk order",
      "call customer",
      "rto",
      "order cancel reason",
    ],
    navigationPath: ["Sales", "Orders", "Open an order", "Order Verification"],
    route: "/admin/orders",
    actionLabel: "Open Orders",
    instructionsUrdu:
      "Har naye **Cash on Delivery** order par order page ke upar **Order Verification** card aata hai. Is mein risk level (LOW / MEDIUM / HIGH), mashwara (Confirm, Customer ko call karein, ya Manual review) aur wajah likhi hoti hai - jaise pehla order, address adhoora, ya pichle RTO. Ye sirf mashwara hai, faisla aap ka hai.\n\n1. **Call Customer** ya **WhatsApp Customer** (free, message pehle se likha hota hai) se customer se tasdeeq karein.\n2. **Confirm Order** dabayein aur list se note chunein (jaise 'Customer confirmed on call'), ya 'Other' chun kar khud likhein.\n3. Order jaali ho to **Reject Order** dabayein - wajah chunna zaroori hai. Order cancel ho jayega.\n\nConfirm hone se pehle order Processing/Packed/Shipped nahi ho sakta aur courier details save nahi hongi. Order Status dropdown se cancel karna ho to Cancel box mein wajah likhna zaroori hai. Prepaid (bank transfer / JazzCash) orders par ye card nahi aata.",
    instructionsEnglish:
      "Every new Cash on Delivery order shows an Order Verification card on the order page with a risk level (LOW / MEDIUM / HIGH), a recommendation (Confirm, Call the customer, or Manual review) and the reasons - e.g. first order, incomplete address, previous RTOs. It is advice only; you decide.\n\n1. Use Call Customer or WhatsApp Customer (free, pre-written message) to check with the customer.\n2. Press Confirm Order and pick a note from the list (e.g. 'Customer confirmed on call'), or choose 'Other' and type one.\n3. If it's not genuine, press Reject Order - a reason is required - and the order is cancelled.\n\nUntil it's confirmed, the order can't move to Processing/Packed/Shipped and courier details can't be saved. Cancelling from the status controls also needs a reason. Prepaid (bank transfer / JazzCash) orders don't get this card.",
    exampleQuestions: [
      "COD order kaise confirm karun?",
      "Order verification card kya hai?",
      "Fake order kaise reject karun?",
      "Order processing par kyun nahi ja raha?",
    ],
  },
  {
    id: "new_order_sound",
    title: "New Order Sound Alert",
    category: "sales",
    keywords: [
      "new order sound",
      "order notification sound",
      "order aane par awaz",
      "order par awaz",
      "awaz nahi",
      "awaz",
      "sound nahi aa rahi",
      "sound",
      "sound nahi",
      "nahi bajti",
      "nahi bajta",
      "chime",
      "order alert",
      "ding",
      "notification bell",
    ],
    navigationPath: ["Store Admin (any page)"],
    route: "/admin/orders",
    actionLabel: "Open Orders",
    instructionsUrdu:
      "Jab Store Admin khula ho to har naye order par **'New order received'** notification aata hai aur ek chhoti si awaz bajti hai (har ~10 second mein naye orders check hote hain). Browser ke qaide ki wajah se awaz tabhi bajegi jab aap ne admin page par **kam az kam ek dafa click** kiya ho - page kholte hi kahin bhi ek click kar dein. Computer/phone ki awaz band na ho, aur browser tab mute na ho. Ye feature bilkul free hai.",
    instructionsEnglish:
      "While Store Admin is open, every new order shows a 'New order received' notification and plays a short chime (new orders are checked about every 10 seconds). Browsers only allow sound after you've clicked somewhere on the admin page at least once - click anywhere after opening it. Make sure your device volume is on and the browser tab isn't muted. This feature is free.",
    exampleQuestions: [
      "Naye order par awaz kyun nahi aa rahi?",
      "Order aane ka pata kaise chalega?",
    ],
  },
  {
    id: "store_currency",
    title: "Store Currency (Rs / $)",
    category: "settings",
    keywords: [
      "currency",
      "rs",
      "rupees",
      "rupay",
      "dollar",
      "prices mein",
      "price symbol",
      "$ ki jagah",
      "price symbol",
      "currency change",
      "pkr",
    ],
    navigationPath: ["Settings", "General", "Currency"],
    route: "/admin/settings",
    actionLabel: "Open Settings",
    instructionsUrdu:
      "Store ki currency **Settings → General** mein set hoti hai (Currency aur Currency Symbol, jaise PKR / Rs.). Jo yahan set ho wahi har jagah dikhta hai: products, cart, checkout, order tracking, order emails, WhatsApp messages aur Store Admin ke orders, dashboard, analytics aur finance. Symbol badalne ke baad Save Changes dabayein.",
    instructionsEnglish:
      "Your store's currency is set under Settings → General (Currency and Currency Symbol, e.g. PKR / Rs.). Whatever you set there is used everywhere: products, cart, checkout, order tracking, order emails, WhatsApp messages and Store Admin orders, dashboard, analytics and finance. Press Save Changes after changing it.",
    exampleQuestions: ["Currency kaise badlun?", "Prices mein $ ki jagah Rs kaise dikhaun?"],
  },
  {
    id: "order_confirmation_email",
    title: "Order Confirmation Email to Customers",
    category: "settings",
    keywords: [
      "order email",
      "order confirmation email",
      "customer email",
      "email kis naam se jati",
      "reply email",
      "email logo",
      "support email",
    ],
    navigationPath: ["Settings", "Email"],
    route: "/admin/settings",
    actionLabel: "Open Settings",
    instructionsUrdu:
      "Jab customer checkout par apna email deta hai to use order confirmation email jati hai - **aap ke store ke naam, logo aur theme color ke saath** (Webriiz ke naam se nahi), jis mein products, total aur delivery address hota hai. Customer email ka **reply karega to wo aap ke store ke email par aayega** - is ke liye **Settings → Email** mein 'Support Email Address' set karein (warna store ka email use hota hai). Email checkout par optional hai; jo customer email na de use email nahi jati.",
    instructionsEnglish:
      "When a customer gives their email at checkout, they get an order confirmation email branded with your store's name, logo and theme colour (not Webriiz), listing the products, total and delivery address. When the customer replies, it goes to your store's email - set 'Support Email Address' under Settings → Email (otherwise the store email is used). Email is optional at checkout; customers who don't give one don't get the email.",
    exampleQuestions: [
      "Customer ko order ki email kis naam se jati hai?",
      "Customer email ka reply kahan aayega?",
    ],
  },
];
