import type { SystemThemeConfig, ThemePresetId } from "./theme-types";

export const PRESET_MODERN_MINIMAL: SystemThemeConfig = {
  id: "preset-modern-minimal",
  presetId: "modern-minimal",
  name: "Modern Minimal",
  isActive: true,
  colors: {
    primary: "#0284c7",
    secondary: "#16a34a",
    accent: "#7c3aed",
    success: "#16a34a",
    warning: "#eab308",
    danger: "#dc2626",
    info: "#2563eb",
    background: "#ffffff",
    surface: "#f8fafc",
    card: "#ffffff",
    border: "#e5e7eb",
    heading: "#111827",
    text: "#111827",
    mutedText: "#6b7280",
    headerBackground: "#ffffff",
    footerBackground: "#ffffff",
    topBarBackground: "#111827",
    buttonBackground: "#0f172a",
    buttonHoverBackground: "#1e293b",
    buttonText: "#f8fafc",
    link: "#0284c7",
    linkHover: "#0369a1",
    badgeSale: "#dc2626",
    badgeNew: "#0284c7",
    badgeOutOfStock: "#6b7280",
  },
  darkColors: {
    primary: "#0284c7",
    background: "#0a0a0a",
    card: "#171717",
    text: "#e5e5e5",
    headerBackground: "#171717",
    footerBackground: "#171717",
    border: "#262626",
  },
  typography: {
    headingFont: "poppins",
    bodyFont: "poppins",
    baseFontSizePx: 16,
    lineHeight: 1.5,
    letterSpacingPx: 0,
    headingWeight: 600,
    bodyWeight: 400,
    buttonWeight: 500,
  },
  logos: {},
  buttons: {
    radius: "full",
    heightPx: 48,
    shadow: "xl",
    hoverEffect: "none",
    border: false,
    paddingX: 24,
    paddingY: 14,
    transitionSpeed: "normal",
  },
  cards: {
    radius: "xl",
    shadow: "none",
    border: false,
    hoverEffect: "none",
    spacingPx: 16,
    background: "#ffffff",
  },
  productCard: {
    variant: "sleek-pill",
    aspectRatio: "1:1",
    imageRadius: "xl",
    cardRadius: "none",
    hoverEffect: "none",
    buttonStyle: "solid",
    showSecondaryImageOnHover: true,
    showQuickAdd: true,
    badgePosition: "top-left",
    showWishlist: true,
    showCompare: true,
    showQuickView: true,
  },
  productDetail: {
    variant: "minimal",
    galleryStyle: "clickable-thumbnails",
    purchasePanelStyle: "standard",
    showCompare: true,
  },
  cart: {
    variant: "minimal",
    drawerStyle: "standard",
    itemLayout: "detailed",
  },
  header: {
    variant: "centered",
    logoAlignment: "left",
    sticky: true,
    transparent: false,
    heightPx: 80,
    shadow: "none",
    showSearch: true,
    showWishlist: true,
    showCompare: true,
    showAccount: true,
    showCart: true,
    topBar: { enabled: false, showSocialIcons: true },
  },
  footer: {
    variant: "multi-column",
    showCopyright: true,
    copyrightText: "",
    showPaymentIcons: false,
    showNewsletter: false,
  },
  banner: {
    overlayEnabled: true,
    overlayOpacity: 0.3,
    textAlign: "center",
    buttonStyle: "solid",
    heightPx: 400,
  },
  layout: {
    containerWidthPx: 1280,
    gridGapPx: 24,
    sectionPaddingPx: 96,
    sectionMarginPx: 96,
    radius: "xl",
    shadowLevel: "none",
    animationSpeed: "normal",
  },
  darkMode: { enabled: true },
  popup: {
    enabled: false,
    title: "Welcome to our store",
    description: "Subscribe to our newsletter for exclusive discounts and new product updates.",
    buttonText: "Get 10% Off",
    trigger: "page-load",
    delaySeconds: 3,
    frequency: "once-per-session",
    styleVariant: "bottom-slide",
  },
  hero: { variant: "generic" },
  categories: { variant: "generic" },
  promo: { styleVariant: "generic" },
  announcementBar: { variant: "generic" },
};

export const PRESET_PREMIUM_LUXURY: SystemThemeConfig = {
  ...PRESET_MODERN_MINIMAL,
  id: "preset-premium-luxury",
  presetId: "premium-luxury",
  name: "Default Theme",
  colors: {
    ...PRESET_MODERN_MINIMAL.colors,
    primary: "#78350f",
    secondary: "#92400e",
    accent: "#b45309",
    background: "#fafaf9",
    surface: "#f5f5f4",
    card: "#ffffff",
    border: "#e7e5e4",
    heading: "#1c1917",
    text: "#292524",
    mutedText: "#78716c",
    buttonBackground: "#1c1917",
    buttonHoverBackground: "#292524",
    buttonText: "#fafaf9",
  },
  typography: {
    headingFont: "playfairDisplay",
    bodyFont: "workSans",
    baseFontSizePx: 16,
    lineHeight: 1.6,
    letterSpacingPx: 1,
    headingWeight: 600,
    bodyWeight: 400,
    buttonWeight: 500,
  },
  buttons: {
    radius: "none",
    heightPx: 46,
    shadow: "none",
    hoverEffect: "glow",
    border: true,
    paddingX: 32,
    paddingY: 14,
    transitionSpeed: "slow",
  },
  cards: {
    radius: "none",
    shadow: "none",
    border: true,
    hoverEffect: "none",
    spacingPx: 24,
    background: "#ffffff",
  },
  productCard: {
    variant: "editorial",
    aspectRatio: "3:4",
    imageRadius: "none",
    cardRadius: "none",
    hoverEffect: "none",
    buttonStyle: "outline",
    showSecondaryImageOnHover: true,
    showQuickAdd: false,
    badgePosition: "top-left",
    showWishlist: true,
    showCompare: false,
    showQuickView: true,
  },
  productDetail: {
    variant: "luxury",
    galleryStyle: "clickable-thumbnails",
    purchasePanelStyle: "sticky",
    showCompare: true,
  },
  cart: {
    variant: "luxury",
    drawerStyle: "minimal",
    itemLayout: "detailed",
  },
  header: {
    variant: "transparent-overlay",
    logoAlignment: "center",
    sticky: true,
    transparent: true,
    heightPx: 96,
    shadow: "none",
    showSearch: true,
    showWishlist: true,
    showCompare: false,
    showAccount: true,
    showCart: true,
    topBar: { enabled: false, showSocialIcons: false },
  },
  footer: {
    variant: "minimal-centered",
    showCopyright: true,
    showPaymentIcons: false,
    showNewsletter: true,
  },
  popup: { ...PRESET_MODERN_MINIMAL.popup, styleVariant: "center-modal" },
  hero: { variant: "luxe" },
  categories: { variant: "luxe" },
  promo: { styleVariant: "luxe" },
  announcementBar: { variant: "luxe" },
};

/**
 * Consolidated to a single retained theme (Phase 1 cleanup) - the other 8
 * former presets (bold-commerce/fashion-editorial/beauty-cosmetics/
 * electronics-tech/streetwear-urban/furniture-home/grocery-fresh, plus the
 * base modern-minimal itself) were mostly the same layout with different
 * colors, not genuinely distinct themes. `PRESET_MODERN_MINIMAL` above is
 * kept only because this preset structurally spreads it as its base -
 * existing tenants still on a removed presetId keep rendering exactly as
 * before, since their persisted themeSettings doc already has every field
 * populated (see deepMergeTheme() in theme-repository.ts) and the underlying
 * variant components (MinimalHero, BoldStreetCategories, TechDealsPromo,
 * CenteredHeader, MegaMenuHeader, MultiColumnFooter, etc.) are untouched -
 * only the preset *catalog* shrank, not the reusable component layer future
 * themes will build on.
 */
export const THEME_PRESETS: Partial<Record<ThemePresetId, SystemThemeConfig>> = {
  "premium-luxury": PRESET_PREMIUM_LUXURY,
};

export const DEFAULT_SYSTEM_THEME = PRESET_PREMIUM_LUXURY;
